#!/usr/bin/env node
/**
 * Data Seeder — fetches GitHub repos tagged with 'featured-project' or 'portfolio'
 * and generates lib/data/autogen/gh-projects.ts for use in the site.
 *
 * Usage:
 *   node scripts/dataseedr.js
 *   node scripts/dataseedr.js --token=<GitHub PAT>
 *   node scripts/dataseedr.js --token=<PAT> --owner=someoneelse
 */

import { writeFileSync, mkdirSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─── Config ──────────────────────────────────────────────────────────────────

const TOPICS_TO_MATCH = ["featured-project", "portfolio"]
const SYSTEM_TOPICS = new Set([...TOPICS_TO_MATCH, "hacktoberfest"])
const DEFAULTS = { owner: "brionmario", perPage: 100 }
const OUTPUT_PATH = join(__dirname, "..", "lib", "data", "autogen", "gh-projects.ts")

// ─── CLI args ─────────────────────────────────────────────────────────────────

function getArg(name) {
  const match = process.argv.find((a) => a.startsWith(`--${name}=`))
  return match ? match.split("=").slice(1).join("=") : null
}

const TOKEN = getArg("token")
const OWNER = getArg("owner") ?? DEFAULTS.owner

// ─── Helpers ──────────────────────────────────────────────────────────────────

const log = (...a) => console.log(...a)
const err = (...a) => console.error(...a)

function prettifyName(name) {
  return name
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

const headers = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
}

// ─── GitHub API ───────────────────────────────────────────────────────────────

async function fetchAllRepos() {
  let page = 1
  let all = []

  while (true) {
    log(`  Fetching page ${page}…`)
    const res = await fetch(
      `https://api.github.com/users/${OWNER}/repos?page=${page}&per_page=${DEFAULTS.perPage}&sort=updated`,
      { headers }
    )

    if (!res.ok) {
      const remaining = res.headers.get("x-ratelimit-remaining")
      err(`  ✗ GitHub API error: ${res.status} ${res.statusText}`)
      if (remaining === "0") err("  ✗ Rate limit hit. Pass --token=<PAT> to increase the limit.")
      process.exit(1)
    }

    const repos = await res.json()
    if (!repos.length) break

    all = [...all, ...repos]
    if (repos.length < DEFAULTS.perPage) break
    page++
  }

  return all
}

// ─── Mapping ──────────────────────────────────────────────────────────────────

function mapRepo(repo) {
  const tags = [
    repo.language,
    ...repo.topics.filter((t) => !SYSTEM_TOPICS.has(t)),
  ].filter(Boolean)

  return {
    id: repo.name,
    name: prettifyName(repo.name),
    org: repo.owner?.type === "Organization" ? repo.owner.login : "Personal",
    description: repo.description ?? "",
    githubUrl: repo.html_url,
    ...(repo.homepage ? { homepage: repo.homepage } : {}),
    tags,
    stars: repo.stargazers_count,
    forks: repo.forks_count,
    language: repo.language ?? null,
    featured: true,
  }
}

// ─── Output ───────────────────────────────────────────────────────────────────

function writeOutput(projects) {
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true })

  const body = `// AUTO-GENERATED by scripts/dataseedr.js — do not edit manually.
// Run: pnpm dataseed to regenerate.
// Last generated: ${new Date().toISOString()}

export const ghProjects = ${JSON.stringify(projects, null, 2)}
`
  writeFileSync(OUTPUT_PATH, body, "utf-8")
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  log("\n🌱  brionmario.com Data Seeder\n")
  log(`   Owner : ${OWNER}`)
  log(`   Auth  : ${TOKEN ? "Bearer token ✓" : "Unauthenticated (60 req/hr limit)"}\n`)

  log("📡  Fetching repos from GitHub…")
  const all = await fetchAllRepos()
  log(`    Found ${all.length} public repos.\n`)

  const matched = all.filter(
    (r) => !r.private && r.topics?.some((t) => TOPICS_TO_MATCH.includes(t))
  )

  if (!matched.length) {
    err(`⛔  No repos matched topics [${TOPICS_TO_MATCH.join(", ")}].`)
    err("    Tag repos on GitHub with one of those topics and re-run.\n")
    process.exit(1)
  }

  log(`🔍  Matched ${matched.length} repo(s) with topics [${TOPICS_TO_MATCH.join(", ")}]:`)
  const projects = matched.map(mapRepo)
  projects.forEach((p) => log(`    • ${p.name}  (${p.org})  ⭐ ${p.stars}`))

  writeOutput(projects)
  log(`\n✅  Written → ${OUTPUT_PATH}\n`)
}

main().catch((e) => {
  err(`\n❌  ${e.message}\n`)
  process.exit(1)
})
