// AUTO-GENERATED by scripts/dataseedr.js — do not edit manually.
// Run: pnpm dataseed to regenerate.
// Last generated: 2026-05-04T19:04:34.072Z

export const ghProjects = [
  {
    "id": "brionmario.com",
    "name": "Brionmario.Com",
    "org": "Personal",
    "description": "👨🏽‍💻 Welcome to the source code for my personal website (Re-written with Next.js)",
    "githubUrl": "https://github.com/brionmario/brionmario.com",
    "homepage": "https://brionmario.com",
    "tags": [
      "TypeScript",
      "blog",
      "nextjs",
      "turborepo",
      "typescript"
    ],
    "stars": 3,
    "forks": 0,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "asgardeo-integrations",
    "name": "Asgardeo Integrations",
    "org": "Personal",
    "description": "Sample applications to demonstration login integrations using `@asgardeo/auth-react`",
    "githubUrl": "https://github.com/brionmario/asgardeo-integrations",
    "tags": [
      "CSS",
      "asgardeo",
      "ciam",
      "iam",
      "integration",
      "react",
      "sdk",
      "wso2"
    ],
    "stars": 1,
    "forks": 7,
    "language": "CSS",
    "featured": true
  },
  {
    "id": "dev-server-ports",
    "name": "Dev Server Ports",
    "org": "Personal",
    "description": "😎 Handle dev server ports like a boss",
    "githubUrl": "https://github.com/brionmario/dev-server-ports",
    "tags": [
      "TypeScript"
    ],
    "stars": 0,
    "forks": 0,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "identity-apps",
    "name": "Identity Apps",
    "org": "Personal",
    "description": "End-user apps in WSO2 Identity Server",
    "githubUrl": "https://github.com/brionmario/identity-apps",
    "homepage": "https://identity-apps.vercel.app",
    "tags": [
      "TypeScript"
    ],
    "stars": 1,
    "forks": 1,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "ui-configs",
    "name": "Ui Configs",
    "org": "Personal",
    "description": "The Shareable configurations to maintain consistency across Brion Mario's UI code bases.",
    "githubUrl": "https://github.com/brionmario/ui-configs",
    "tags": [
      "JavaScript",
      "eslint",
      "prettier",
      "shareable-configs"
    ],
    "stars": 1,
    "forks": 0,
    "language": "JavaScript",
    "featured": true
  },
  {
    "id": "gatsby-starter",
    "name": "Gatsby Starter",
    "org": "Personal",
    "description": "🏆 A fully loaded starter kit for Gatsby development to get your website up and running in minutes.",
    "githubUrl": "https://github.com/brionmario/gatsby-starter",
    "homepage": "https://gatsbystartermain82236.gatsbyjs.io/",
    "tags": [
      "TypeScript",
      "cypress",
      "eslint",
      "fontawesome",
      "gatsby",
      "gatsby-starter",
      "mdx",
      "portfol",
      "react-i18next",
      "react-test",
      "react-testing-library",
      "sass",
      "stylelint",
      "tailwindcss",
      "typescript"
    ],
    "stars": 3,
    "forks": 2,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "is-samples",
    "name": "Is Samples",
    "org": "Personal",
    "description": "A repo containing WSO2 Identity Server usage samples",
    "githubUrl": "https://github.com/brionmario/is-samples",
    "tags": [
      "TypeScript",
      "oidc",
      "react",
      "samples",
      "wso2",
      "wso2-identity-server"
    ],
    "stars": 2,
    "forks": 13,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "asgardeo-branding",
    "name": "Asgardeo Branding",
    "org": "Personal",
    "description": "This repo contains instructions and artifacts which'll help achieve organization level UI branding in Asgardeo",
    "githubUrl": "https://github.com/brionmario/asgardeo-branding",
    "homepage": "https://myaccount.asgardeo.io/t/koalasports",
    "tags": [
      "CSS",
      "asgardeo",
      "branding",
      "ciam",
      "indentitycloud",
      "organizations"
    ],
    "stars": 1,
    "forks": 1,
    "language": "CSS",
    "featured": true
  },
  {
    "id": "oxygen-ui-poc",
    "name": "Oxygen Ui Poc",
    "org": "Personal",
    "description": "[WIP] WSO2 Design System",
    "githubUrl": "https://github.com/brionmario/oxygen-ui-poc",
    "homepage": "https://oxygen-ui.vercel.app/",
    "tags": [
      "TypeScript"
    ],
    "stars": 1,
    "forks": 2,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "php-starter",
    "name": "Php Starter",
    "org": "Personal",
    "description": "☄️  A quick start kit for PHP based website development with an optimised Gulp build process.",
    "githubUrl": "https://github.com/brionmario/php-starter",
    "homepage": "https://php-starter-seed.herokuapp.com",
    "tags": [
      "PHP",
      "bower",
      "composer",
      "es6",
      "gulp",
      "heroku",
      "npm",
      "php",
      "sass",
      "seed",
      "starter",
      "starter-kit"
    ],
    "stars": 2,
    "forks": 5,
    "language": "PHP",
    "featured": true
  },
  {
    "id": "angular-switchable-grid",
    "name": "Angular Switchable Grid",
    "org": "Personal",
    "description": "A simple grid , which can be used to view data as tile blocks or as a typical list. ",
    "githubUrl": "https://github.com/brionmario/angular-switchable-grid",
    "tags": [
      "TypeScript"
    ],
    "stars": 1,
    "forks": 0,
    "language": "TypeScript",
    "featured": true
  },
  {
    "id": "html-starter",
    "name": "Html Starter",
    "org": "Personal",
    "description": "🚀 A Gulp starter kit for static website development with an optimised Gulp build process.",
    "githubUrl": "https://github.com/brionmario/html-starter",
    "homepage": "https://html-starter.netlify.com",
    "tags": [
      "HTML",
      "boilerplate",
      "bower",
      "es6",
      "gulp",
      "heroku",
      "html5",
      "netlify",
      "npm",
      "sass",
      "seed",
      "starter",
      "starter-kit"
    ],
    "stars": 3,
    "forks": 3,
    "language": "HTML",
    "featured": true
  },
  {
    "id": "jquery-mobile-starter",
    "name": "Jquery Mobile Starter",
    "org": "Personal",
    "description": "💥  A quick start kit for jQuery Mobile Framework based website development with SASS support",
    "githubUrl": "https://github.com/brionmario/jquery-mobile-starter",
    "homepage": "https://jquery-mobile-starter.herokuapp.com/",
    "tags": [
      "SCSS",
      "framework",
      "gulp",
      "jquery",
      "jquery-mobile",
      "php",
      "responsive",
      "sass"
    ],
    "stars": 2,
    "forks": 1,
    "language": "SCSS",
    "featured": true
  }
]
